"""Initial migration

Revision ID: 1266bce5f4e3
Revises: 
Create Date: 2025-01-20 15:20:03.257609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1266bce5f4e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'ARCHIVED', 'BINNED', name='notestate'), nullable=False),
    sa.Column('pin', sa.Enum('NOTPINNED', 'PINNED', name='notepin'), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    # ### end Alembic commands ###
